version: "3.7"
services:
  app:
    image: nginx:alpine
    container_name: lottery-front-app
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=lotterycamp.local
      - LETSENCRYPT_HOST=lotterycamp.local
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

networks:
  default:
    external:
      name: projects_default
