export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
export const ADD_LOADING_MESSAGE = "ADD_LOADING_MESSAGE";
export const DELETE_LOADING_MESSAGE = "DELETE_LOADING_MESSAGE";

export const SET_AUTH = "SET_AUTH";
export const SET_EVENTS = "SET_EVENTS";
export const SET_APP_SETTINGS = "SET_APP_SETTINGS";
export const SET_LOTTERY_WINNERS = "SET_LOTTERY_WINNERS";
export const SET_LOTTERY_SLOT = "SET_LOTTERY_SLOT";
export const SET_LOTTERY_PLAYERS = "SET_LOTTERY_PLAYERS";
export const ADD_LOTTERY_PLAYER = "ADD_LOTTERY_PLAYER";
export const SET_LOTTERY_RESULT = "SET_LOTTERY_RESULT";
export const SET_MODAL = "SET_MODAL";

