export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
export const ADD_LOADING_MESSAGE = "ADD_LOADING_MESSAGE";
export const DELETE_LOADING_MESSAGE = "DELETE_LOADING_MESSAGE";

export const SET_AUTH = "SET_AUTH";
export const SET_EVENTS = "SET_EVENTS";
export const SET_APP_SETTINGS = "SET_APP_SETTINGS";
export const SET_LOTTERY_WINNERS = "SET_LOTTERY_WINNERS";
export const SET_LOTTERY_SLOT = "SET_LOTTERY_SLOT";
export const SET_LOTTERY_PLAYERS = "SET_LOTTERY_PLAYERS";
export const ADD_LOTTERY_PLAYER = "ADD_LOTTERY_PLAYER";
export const SET_LOTTERY_DATA = "SET_LOTTERY_DATA";
export const SET_MODAL = "SET_MODAL";
export const SET_SETTINGS = "SET_SETTINGS";
export const SET_CURRENCIES = "SET_CURRENCIES";
export const SET_USER = "SET_USER";
export const SET_LOTTERY_PICKED_NUMBERS = "SET_LOTTERY_PICKED_NUMBERS";
export const SET_LAST_SLOT = "SET_LAST_SLOT";

